version: '3'
services:
  database:
    container_name: database
    image: 'mysql:5.7.16'
    volumes:
      - './.data/db:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_USER}"
      MYSQL_USER: "${DATABASE_NAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '3306:3306'
  redis:
    container_name: redis
    image: 'redis:3.2.1'
    ports:
      - '6379:6379'
  backend:
    build:
      context: ../..
      dockerfile: "deployments/local/Dockerfile"
    environment:
      IMAGE_FLAVOR: backend
      DATABASE_HOST: database
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      HTTPS_LINKS_ONLY: 'false'
      TOKEN_SECRET: "${TOKEN_SECRET}"
      TOKEN_ISSUER: 'Open Source Moderator (Dev)'
      REDIS_URL: 'redis://redis:6379'
      FRONTEND_URL: '${URL_BASE}:8000'
      APP_NAME: 'Moderator (Dev)'
      REDIRECT_OAUTH_TO: 'referrer'
      PORT: 8080
    ports:
      - "8080:8080"
    links:
        - database
        - redis
  frontend:
    build:
      context: ../..
      dockerfile: "deployments/local/Dockerfile"
    environment:
      IMAGE_FLAVOR: frontend
      API_URL: '${URL_BASE}:8080'
      APP_NAME: 'Moderator (Dev)'
      PORT: 8000
    ports:
      - "8000:8000"
#  processing:
#    build:
#      context: ../..
#      dockerfile: "deployments/local/Dockerfile"
#    environment:
#      IMAGE_FLAVOR: "sync-${MODERATOR_FLAVOR$}
#      DATABASE_HOST: database
#      DATABASE_NAME: "${DATABASE_NAME}"
#      DATABASE_USER: "${DATABASE_USER}"
#      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
#      REDIS_URL: 'redis://redis:6379'
#    ports:
#      - "8000:8000"
#    links:
#        - database
#        - redis
