apiVersion: v1
kind: Service
metadata:
  name: moderator-networking
spec:
  type: LoadBalancer
  ports:
    - name: frontend
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: conversationai-moderator